#!/usr/bin/perl -T -CSDAL

use warnings;
use strict;
use IServ::User;
use IServ::Valid;
use Stsbl::IServ::IO;
use Stsbl::IServ::Security;

my $m_ip = qr/[\d.:]{1,64}/;

my $login_pwd = $ENV{PASSWORD} // $ENV{SESSPW};
my ($login_ip) = ($ENV{IP} // "") =~ /^($m_ip)$/;
my ($login_ip_fwd) = ($ENV{IPFWD} // "") =~ /^($m_ip)$/;
my ($auth_level, $auth_user);
undef %ENV;

if (@ARGV < 2)
{
    print STDERR "Usage: act_cancel_membership LOGIN GROUP\n";
    print STDERR "Environment: PASSWORD, IP, IPWD\n";
    exit 1
}

my ($login_act, $group) = @ARGV;

# untaint
$login_act = IServ::Valid::User $login_act;
$group = IServ::Valid::Group $group;

set_ips $login_ip, $login_ip_fwd;
set_credentials $login_act, $login_pwd;
sessauth_auth "act_cancel_membership";

# permission check
req_auth;
req_priv "act_cancel_membership";
req_flag $group, "canceling_allowed";

# remove user from group
my ($users, $groups) = map [split ","], $login_act, $group;
my $success = IServ::User::MembersDel @$users, @$groups;

exit 1 unless $success;
