# src/Stsbl/CancelGroupMembershipBundle/Resources/config/services.yml
services:
    stsbl.cancelgroupmembership.security.cancel_voter:
        class: Stsbl\CancelGroupMembershipBundle\Security\Authorization\Voter\CancelVoter
        arguments: ["@security.access.decision_manager", "@doctrine.orm.entity_manager"]
        public: false
        tags:
            - { name: security.voter }
    
    stsbl.cancelgroupmembership.menu:
        class: Stsbl\CancelGroupMembershipBundle\EventListener\MenuSubscriber # Out MenuSubscriber Class
        tags:
            - { name: kernel.event_subscriber } # Tells IServ about our subsriber
          
    stsbl.cancelgroupmembership.service.cancel:
        class: Stsbl\CancelGroupMembershipBundle\Service\CancelMembership
        arguments: ["@iserv.shell", "@iserv.security_handler"]
